### ISSUE TITLE
You should be able to generate constants in c++

### ISSUE THREAD

**Issue by saroad2** [saroad2/units#21]
For example speed of light, absolute zero temperature, etc.

**Comment by oriash93** [comment]
I recommend a template consisting:
- constant name
- unit type
- unit scale
- value (in that scale)
- a short description (optional)

**Comment by saroad2** [comment]
what about this template?:

* constants group
* constant name
* unit scale
* value
* a short description

I think it's better because sometimes you want to group constants even though they have different types.
for example, I would like to have a group named "earth properties" which includes its axis radiuses (length type), its mass (mass type), its spinning speed (angular speed) etc.

The idea of the short description is a great one which I didn't think of! do you think we need this somewhere else also?

**Comment by oriash93** [comment]
>The idea of the short description is a great one which I didn't think of! do you think we need this somewhere else also? 

Can't think of anything right now 🤔
