### ISSUE TITLE
Inconsistent scale calculation in duration classes

### ISSUE THREAD

**Issue by gioragutt** [saroad2/units#4]
Regarding [Duration](https://github.com/saroad2/units/blob/master/include/duration_units.h),

Lines `53-55` and `64-66` calculate scale based on conversions from `chrono` classes for `minutes_tag` and `hours_tag`, unlike `days_tag` and `years_tag` that are calculated based on their previous tags scale.

Do you do that because there's no suitable method for these scales? Perhaps it's better for clarity to simplify calculation in `minutes_tag` and `hours_tag` instead of using conversions from `chrono`?

Also, you can make a template method out of what's going on in the lines I've stated above, it might help in clarity if you want to keep conversions based on `chrono`.

**Comment by saroad2** [comment]
Wherever I can use chrono, i use it.
Since chrono does not dupoort days or years, I added the scale multiplication myself
