### ISSUE TITLE
Invalid order of tags passed to duration classes

### ISSUE THREAD

**Issue by gioragutt** [saroad2/units#5]
Regarding [Duration](https://github.com/saroad2/units/blob/master/include/duration_units.h),

In `Days` and `Years` (as you do in all classes that are `NumericValue`s),  
you pass the unit tag first (`duration_tag`), and then the scale tag (`days_tag`).  
In classes that are created with `Duration`, you pass the scale tag before the unit tag
F.E:
* `using Minutes = Duration<std::chrono::minutes, minutes_tag, duration_tag>;`
* `using Days = NumericValue<days_tag, duration_tag>;`

**Comment by saroad2** [comment]
As you can see in the exact example you gave, it is exactly he opposite: first we inset the `ScaleTag` and than the `TypeTag`.
It is tested inside unit tests and it's ok :)
